version: "3"

includes:
  go-test:
    taskfile: go/Taskfile.test.yml
    dir: .
  go-devel:
    taskfile: go/Taskfile.devel.yml
    dir: .
  vscodeext-test:
    taskfile: vscodeext/Taskfile.test.yml
    dir: .
  vscodeext-devel:
    taskfile: vscodeext/Taskfile.devel.yml
    dir: .

tasks:
  # Meta-task to build all containers
  build-all:
    desc: Build all dev environment containers
    cmds:
      - task: go:build

  list:
    desc: List all available tasks
    cmds:
      - task --list
