#!/bin/bash
export JEKYLL_VERSION=latest
export JEKYLL_TOMAS303=/home/tomas/development/tomas303/tomas303.github.io
# -c "bundle config set --local path '/opt' && bundle update || true  && jekyll serve --watch --drafts --force_polling -t"

podman run --rm --name jekyllserve  \
  -it \
  -e JEKYLL_ROOTLESS=1 \
  -p 4000:4000 \
  -v "$JEKYLL_TOMAS303:/srv/jekyll:Z" \
  jekyll/jekyll:$JEKYLL_VERSION \
  jekyll serve --watch --drafts --force_polling -t
