#!/bin/bash

#docker run --privileged -v /mnt/datashareone/sources:/sources --rm -it --name lazarus lazarus
PATH=/sbin:$PATH
podman run --privileged \
	-v /mnt/datashareone/sources:/sources \
	-v /mnt/datashareone/sources/ideconfigs/lazarus:/lazarusconfigdir \
	-e LazarusConfigDir=/lazarusconfigdir \
	-p 5900:5900 \
	-it \
	--rm \
	--name lazarus \
	lazarus  
